version: '3'
services:
  db: # -----------------------------------------------------------------------
    ports:
      - "${PROJECT_IP:-0.0.0.0}:5432:5432"

  nginx: # --------------------------------------------------------------------
    ports:
      - "${PROJECT_IP:-0.0.0.0}:80:80"

  app: # ------------------------------------------------------------------
    volumes:
      - ./app:/app
    command:
            sh -c './manage.py collectstatic --noinput ; ./manage.py runserver 0.0.0.0:8000'
