version: '3'
services:
  db: # -----------------------------------------------------------------------
    image: postgres:13.3-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./deploy/data/backup/db:/var/lib/backup/data
      - ./db/bin:/var/lib/backup/bin
    env_file:
      - ./deploy/envs/postgres.env

  nginx: # --------------------------------------------------------------------
    build:
      context: nginx
      dockerfile: Dockerfile
      args:
        PROJECT_DOMAIN: ${PROJECT_DOMAIN}
    depends_on:
      - app
      - static
    ports:
      - "${PROJECT_IP:-0.0.0.0}:${PROJECT_PORT}:80"
      - "${PROJECT_IP:-0.0.0.0}:${PROJECT_PORT_SSL}:443"
    env_file:
      - ./.env
    volumes:
       - http-media-public:/www/media
       - http-static:/www/static
       - nginx-config:/etc/nginx/conf.d
       - nginx-certificates:/etc/letsencrypt

  app: # ------------------------------------------------------------------
    build:
      context: app
      dockerfile: Dockerfile
      args:
        PIPENV_OPTIONS: "${PIPENV_OPTION}"
        PIPENV_KEEP_OUTDATED: "${PIPENV_KEEP_OUTDATED}"
    depends_on:
      - db
    env_file:
      - ./.env
      - ./deploy/envs/postgres.env
      - ./deploy/envs/app.env
    volumes:
      - ./deploy/logs/app:/app/logs
      - http-media:/app/media
      - http-media-public:/www/media/public
      - http-static:/app/static

  static: # -------------------------------------------------------------------
    build:
      context: app-static
      dockerfile: Dockerfile
    volumes:
       - http-media-public:/www/media
       - http-static:/www/static

volumes:
  db-data:
  http-media:
  http-media-public:
  http-static:
  nginx-config:
  nginx-certificates:
